/*
 * CYBERFORGE Study Library content system.
 * The notes retain the graphite-and-lime containment-console identity while presenting
 * original, handwritten-notebook-style lessons. Every page is lawful, defensive, and
 * intended for browser-local study rather than real-world access or testing.
 */

export type StudyTopic = { title: string; note: string; practice: string };
export type StudyVolume = {
  id: string;
  code: string;
  title: string;
  accent: "lime" | "blue" | "amber" | "violet";
  description: string;
  lawfulUse: string;
  boundary: string;
  topics: StudyTopic[];
};
export type StudyPage = {
  number: number;
  volume: StudyVolume;
  topic: StudyTopic;
  note: string;
};

const volumes: StudyVolume[] = [
  {
    id: "foundations", code: "VOL 01", title: "Security Foundations", accent: "lime",
    description: "Build a calm, lawful security mindset before touching a command line. These notes connect responsibility, risk, privacy, and defensive decision-making.",
    lawfulUse: "Use these ideas to protect your own accounts, document authorized work, and communicate clearly with the system owner.",
    boundary: "Never treat curiosity as authorization. Written permission, a named asset, a time window, and an owner contact come first.",
    topics: [
      { title: "Security as a practice", note: "Security is an ongoing process of reducing avoidable harm, not a one-time tool run.", practice: "Write three habits that protect your own device each week." },
      { title: "The CIA triad", note: "Confidentiality, integrity, and availability help describe what a control is protecting.", practice: "Classify one personal app risk using all three terms." },
      { title: "Assets and owners", note: "Every asset needs an accountable owner who can authorize work and receive findings.", practice: "List assets you own and their responsible person." },
      { title: "Threats, vulnerabilities, and risk", note: "A weakness becomes meaningful when it can affect a valuable asset in a real context.", practice: "Describe a low-risk example without naming a third-party system." },
      { title: "Authorization before action", note: "Permission defines what you may test, how, when, and whom to contact if something changes.", practice: "Draft a one-sentence scope statement for a fictional lab." },
      { title: "Ethics and professional conduct", note: "A professional protects people, avoids unnecessary data, and reports carefully.", practice: "Write a rule you will follow when handling sample logs." },
      { title: "Personal data and privacy", note: "Logs, screenshots, and exports can contain personal data even when a task appears technical.", practice: "Identify which fields should be redacted from an example incident note." },
      { title: "Least privilege", note: "Grant only the access needed for the current task, then review and remove it when no longer required.", practice: "Name one account on your own device that should not be an administrator." },
      { title: "Defense in depth", note: "Layered controls reduce the chance that one mistake becomes a serious incident.", practice: "Map password manager, MFA, updates, and backups to separate layers." },
      { title: "Secure defaults", note: "A safe default protects the user before they know every advanced setting.", practice: "Check one privacy or update setting on a device you own." },
      { title: "Attack surface reduction", note: "Fewer exposed services, unused accounts, and unnecessary permissions mean fewer opportunities for failure.", practice: "List one unused app or permission you can review later." },
      { title: "Authentication and identity", note: "Identity assurance is stronger when passwords, MFA, recovery, and session rules work together.", practice: "Describe why reusing passwords weakens identity protection." },
      { title: "Password hygiene", note: "Long unique passphrases and a password manager reduce the impact of a single breach.", practice: "Create a non-real example passphrase pattern; do not enter a real password." },
      { title: "Multi-factor authentication", note: "MFA adds a second proof of identity, but recovery methods must also be protected.", practice: "Compare authenticator apps and recovery codes conceptually." },
      { title: "Updates and patching", note: "Updates close known defects and should be planned, tested, and verified where possible.", practice: "Record the update status of one device you own." },
      { title: "Backups and recovery", note: "A backup matters only when it is protected, recent enough, and can be restored.", practice: "Write a simple 3-2-1 backup reminder for your own files." },
      { title: "Security events", note: "An alert is a signal to investigate; it is not automatically proof of compromise.", practice: "Separate observation, inference, and action in a sample event note." },
      { title: "Evidence discipline", note: "Preserve what was observed, where it came from, when it was collected, and who handled it.", practice: "Make a five-field evidence record for a fictional log file." },
      { title: "Communicating findings", note: "A useful finding explains impact, evidence, limits, and the next responsible action.", practice: "Rewrite a vague warning as a concise owner-focused note." },
      { title: "Learning roadmap", note: "Build skill from safety and operating-system basics toward evidence, hardening, and reporting.", practice: "Choose one CYBERFORGE path to complete next." },
    ],
  },
  {
    id: "linux", code: "VOL 02", title: "Linux Foundations", accent: "blue",
    description: "Learn the vocabulary and habits behind a dependable Linux workflow: paths, files, processes, permissions, and careful reading before change.",
    lawfulUse: "Use commands only in environments you own or are authorized to administer, ideally first in a disposable practice environment.",
    boundary: "Commands in CYBERFORGE are simulated examples. They do not change your device, storage, network, or any outside host.",
    topics: [
      { title: "The shell and prompt", note: "The prompt communicates identity, host, current location, and readiness for a command.", practice: "Compare the CYBERFORGE Termux and Kali-style prompts." },
      { title: "Paths and directories", note: "Absolute paths start at the root; relative paths start at your current working directory.", practice: "Use pwd and ls in the virtual lab." },
      { title: "Listing files safely", note: "ls reveals names; ls -la adds hidden items and permission metadata for review.", practice: "Run ls -la logs in the browser-local terminal." },
      { title: "Changing location", note: "cd changes your working directory, so verify location with pwd before modifying files.", practice: "Practice cd logs followed by pwd and cd .." },
      { title: "Reading files", note: "cat, head, tail, and less help inspect content without changing it.", practice: "Read the provided auth log with cat and tail." },
      { title: "Creating files", note: "mkdir and touch create structure, but a clear project folder prevents accidental clutter.", practice: "Create and list a virtual notes directory." },
      { title: "Copying and moving", note: "cp preserves the original while mv changes a path; check the destination first.", practice: "Copy a virtual evidence note and inspect both paths." },
      { title: "Removing carefully", note: "Removal is irreversible in many shells, so inspect the exact target before using rm.", practice: "Read the simulated rm warning in the terminal." },
      { title: "File permissions", note: "Read, write, and execute bits express what an owner, group, and others may do.", practice: "Run ls -la evidence and interpret one mode string." },
      { title: "Ownership", note: "Ownership connects a file to accountable users and groups; change it only with authorization.", practice: "Use the chown lesson prompt, not a real system." },
      { title: "Standard input and output", note: "Commands often read input and write results; redirect only when you understand the destination.", practice: "Trace input and output in a harmless grep example." },
      { title: "Pipelines", note: "Pipelines pass focused output from one review step to another and benefit from small, inspectable stages.", practice: "Use the virtual log pipeline helper from the mission." },
      { title: "Environment variables", note: "Variables hold session configuration, paths, and context; never place secrets carelessly in them.", practice: "Run env in the virtual shell." },
      { title: "Aliases", note: "Aliases save keystrokes but should be transparent so a command’s real behavior is still understood.", practice: "List the virtual aliases with alias." },
      { title: "Manual pages", note: "man pages explain purpose, syntax, options, and cautions before a command is used.", practice: "Open man ls and man chmod in CYBERFORGE." },
      { title: "Processes", note: "A process is a running program with a PID, user, state, and resource footprint.", practice: "Read ps and top sample output without attempting control." },
      { title: "Jobs and signals", note: "Signals communicate with processes, but process control can affect availability and must be deliberate.", practice: "Read the simulated kill guidance." },
      { title: "Archives", note: "Archives package files; treat unfamiliar archives as untrusted until inspected in a safe environment.", practice: "Review the virtual tar and unzip safety response." },
      { title: "Configuration hygiene", note: "Keep changes small, documented, reversible, and tested against a known-good baseline.", practice: "Write a three-step change plan for a fictional config file." },
      { title: "Linux study routine", note: "Read, predict, run in a lab, inspect, and record what happened before moving to the next command.", practice: "Complete Mission 1 in the safe console." },
    ],
  },
  {
    id: "text", code: "VOL 03", title: "Files, Permissions & Text", accent: "amber",
    description: "Turn raw local evidence into readable observations using permissions awareness, search patterns, and small text-processing steps.",
    lawfulUse: "Use these methods on your own notes, intentionally provided samples, or explicitly authorized operational evidence.",
    boundary: "Do not copy personal data into public training spaces or use search tools to hunt through systems outside your scope.",
    topics: [
      { title: "Readable evidence", note: "Start with a source, timestamp, owner, and purpose before drawing a conclusion from a file.", practice: "Open the virtual chain-of-custody note." },
      { title: "Mode strings", note: "Permission strings summarize directory or file type and access rights for owner, group, and others.", practice: "Identify owner and group permissions in ls -la output." },
      { title: "Principle of minimum access", note: "A file should be readable or writable only by the people and services that require it.", practice: "Explain why an evidence file should not be world-writable." },
      { title: "grep for literal evidence", note: "grep finds text patterns; use precise terms and understand false positives before reporting.", practice: "Run grep failed logs/auth.log." },
      { title: "Recursive search", note: "Recursive search is useful in a known directory, but broad searching may expose unrelated material.", practice: "Use grep -r rate-limit logs in the virtual lab." },
      { title: "find by name", note: "find locates known file names within a controlled root and supports careful inventory work.", practice: "Try find . -name '*.log' conceptually." },
      { title: "locate and indexes", note: "locate uses an index that may be old; validate results before trusting them.", practice: "Search the virtual index for evidence." },
      { title: "head and tail", note: "head previews a beginning, while tail helps inspect recent entries in a controlled file.", practice: "Compare head and tail output on auth.log." },
      { title: "Counting with wc", note: "Counts can reveal scale, but counts alone do not establish intent or impact.", practice: "Run wc logs/auth.log in the practice console." },
      { title: "Sorting records", note: "sort gives a stable order for review; preserve the original source separately.", practice: "Read the safe sort guidance." },
      { title: "Duplicate patterns", note: "uniq highlights repeated adjacent lines after sorting, which may point to trends worth reviewing.", practice: "Describe a rate-limit pattern from the sample log." },
      { title: "Columns with cut", note: "Structured text can be split into fields, but delimiters and quoted data require care.", practice: "Identify which field could represent a status code in a sample log." },
      { title: "Text transformations", note: "sed and awk can transform text, so begin by reading and testing on disposable copies.", practice: "Use the concept lesson rather than evaluating arbitrary expressions." },
      { title: "Regular-expression caution", note: "Patterns are powerful and can match more than expected; start narrow and verify samples.", practice: "Write a plain-language search goal before using a pattern." },
      { title: "Log timestamps", note: "A timestamp needs a timezone and source context to support reliable event ordering.", practice: "Find the earliest and latest sample auth event." },
      { title: "Rate-limit evidence", note: "A 429 response can show a defensive control, but confirm the associated policy and owner.", practice: "Search the provided web access log for 429." },
      { title: "Data minimization", note: "Keep only the data needed to explain a finding and redact the rest.", practice: "List fields to remove before sharing a practice excerpt." },
      { title: "Integrity checks", note: "A hash supports change detection for an approved artifact when its expected value is trusted.", practice: "Use the local SHA-256 utility with non-sensitive text." },
      { title: "Notes that can be reviewed", note: "A reviewer should be able to follow your observation back to its source without guessing.", practice: "Write source, command concept, output summary, and limitation." },
      { title: "Text-analysis recap", note: "Good analysis is repeatable, scoped, and framed as evidence plus a modest conclusion.", practice: "Summarize Mission 1 in four careful sentences." },
    ],
  },
  {
    id: "termux", code: "VOL 04", title: "Termux Mobile Notes", accent: "lime",
    description: "Understand a mobile-oriented Linux workflow while treating Android storage, permissions, battery, and personal data with extra care.",
    lawfulUse: "Use Termux only on your own Android device or a device you are authorized to manage, and review app permissions intentionally.",
    boundary: "CYBERFORGE only simulates a Termux-style workflow. It cannot request Android permissions, install software, or open a device shell.",
    topics: [
      { title: "What a mobile shell is", note: "A mobile shell brings command-line concepts to a phone but does not remove the need for careful permissions.", practice: "Compare the Termux-style prompt with the Kali-style prompt." },
      { title: "The Termux prefix", note: "Termux keeps its own application paths, packages, and home directory separate from traditional Linux locations.", practice: "Run termux-info in the simulated terminal." },
      { title: "Home directory habits", note: "A dedicated project folder keeps notes, code, and experiments organized and easier to back up.", practice: "Inspect the virtual authorized-lab path." },
      { title: "Package metadata", note: "Updating package metadata refreshes available package information; it should be reviewed before install decisions.", practice: "Run pkg update in the browser-local lab." },
      { title: "Package installation", note: "Install only what a declared project requires and understand a package’s maintainer and dependencies.", practice: "Try pkg install python as a simulation." },
      { title: "Package upgrades", note: "Upgrades can change behavior, so keep important work backed up and read release notes when available.", practice: "Read the pkg upgrade simulation response." },
      { title: "Storage access", note: "Storage permission exposes personal files, so grant it only when a trusted workflow truly requires it.", practice: "Run termux-setup-storage in CYBERFORGE and read the boundary notice." },
      { title: "Android permissions", note: "A terminal app should not receive contacts, SMS, microphone, or storage access without a clear reason.", practice: "Review the permissions of one installed app on your own phone later." },
      { title: "Battery and background work", note: "Mobile operating systems limit background activity; design tasks that are short, visible, and user-controlled.", practice: "Write why continuous background automation needs careful consent." },
      { title: "Text editors", note: "Editors such as nano support note-taking, but read files before overwriting important content.", practice: "Read the simulated nano guidance." },
      { title: "Python on mobile", note: "Python can support learning and small personal utilities, but copied code needs review before execution.", practice: "Open the Python concept response in the terminal." },
      { title: "Package provenance", note: "A package name is not proof of safety; investigate source, release history, and dependencies.", practice: "List questions to ask before installing a new package." },
      { title: "Secrets on a phone", note: "Tokens, passwords, and private keys can leak through history, screenshots, backups, or shared storage.", practice: "Write three safer alternatives to putting a secret in a command." },
      { title: "Network awareness", note: "Public Wi-Fi and mobile networks deserve the same HTTPS, update, and account-protection habits as any other network.", practice: "Describe when to delay a sensitive task until a safer connection." },
      { title: "SSH concepts", note: "SSH should use verified host keys, least privilege, and authorization; a public course should not open remote sessions.", practice: "Read the CYBERFORGE ssh simulation." },
      { title: "Git concepts", note: "Git records project history, while private repositories and secrets hygiene protect sensitive work.", practice: "Run git status in the virtual repository." },
      { title: "Backups from mobile", note: "Important notes should be copied to an encrypted, recoverable location you control.", practice: "Make a non-sensitive backup checklist." },
      { title: "Troubleshooting calmly", note: "Read the message, isolate one variable, preserve context, and avoid random copy-paste fixes.", practice: "Rewrite an error report with device, command, output, and expected result." },
      { title: "Mobile learning projects", note: "Choose small, legal projects: log parsing, checklists, note templates, or local study scripts.", practice: "Name one project that needs no external target." },
      { title: "Termux study recap", note: "The goal is responsible mobile computing: intentional permissions, known packages, protected information, and repeatable notes.", practice: "Complete the Termux workspace mission." },
    ],
  },
  {
    id: "networking", code: "VOL 05", title: "Networking & Service Awareness", accent: "blue",
    description: "Learn how hosts, ports, protocols, names, and routes support legitimate operations and defensive visibility.",
    lawfulUse: "Observe only systems you own, systems covered by explicit authorization, or declared training environments.",
    boundary: "CYBERFORGE provides static, virtual network observations only. It does not open sockets, send packets, or scan external addresses.",
    topics: [
      { title: "Networks and boundaries", note: "A network is a set of connected systems; segmentation limits how far a problem can spread.", practice: "Identify the 10.42.0.0/24 simulated boundary." },
      { title: "IP addresses", note: "An IP address identifies a network interface in context; it does not by itself identify a person or intent.", practice: "Read the lab interface using ip addr." },
      { title: "Private address space", note: "Private addressing supports internal networks but does not automatically make an activity authorized.", practice: "Explain why scope still matters inside a private network." },
      { title: "Ports and services", note: "Ports direct traffic to services, and each exposed service should have an owner and a purpose.", practice: "Read the simulated ss output." },
      { title: "TCP and UDP", note: "TCP emphasizes ordered delivery; UDP emphasizes lightweight datagrams. Both need appropriate controls.", practice: "Name a general defensive question for each protocol." },
      { title: "DNS concepts", note: "DNS maps names to addresses, so trustworthy configuration and monitoring are important.", practice: "Write a safe hostname-verification checklist." },
      { title: "HTTP and HTTPS", note: "HTTP describes web requests; HTTPS adds transport encryption and server authentication when configured correctly.", practice: "Use the URL format reviewer locally." },
      { title: "TLS trust", note: "Certificates and trusted names help clients authenticate services, but expiry and configuration require monitoring.", practice: "Read the openssl certificate-concept response." },
      { title: "Routing", note: "Routes decide where traffic should go; clear routing and egress policy reduce surprises.", practice: "Read the virtual lab egress policy in system.log." },
      { title: "Firewalls", note: "Firewalls enforce allowed flows, but rule ownership, testing, and logging make them maintainable.", practice: "Describe a least-privilege rule in plain language." },
      { title: "Network segmentation", note: "Separating user, service, management, and test zones reduces lateral exposure.", practice: "Sketch a four-zone home-lab diagram on paper." },
      { title: "Asset inventory", note: "Inventory connects an address or hostname to an owner, purpose, and change history.", practice: "Make an asset row for the virtual lab-web host." },
      { title: "Service ownership", note: "A service without an owner is difficult to patch, monitor, or authorize for testing.", practice: "Add an owner field to a sample service note." },
      { title: "Availability signals", note: "Health endpoints and monitoring can help operations, but they must not expose sensitive information.", practice: "Review the simulated /health reference conceptually." },
      { title: "Connection observations", note: "netstat and ss show local socket state; interpret them as a snapshot, not a complete incident conclusion.", practice: "Read the static socket table safely." },
      { title: "Ping as a concept", note: "Reachability signals can be filtered or misleading, so absence of a reply is not a diagnosis.", practice: "Run ping lab-web in the virtual boundary." },
      { title: "Packet metadata", note: "Metadata such as time, source, destination, and protocol helps build an evidence timeline.", practice: "Use the tcpdump simulation and identify five fields." },
      { title: "Encrypted traffic", note: "Encryption protects content, while metadata and endpoints still need appropriate logging and privacy safeguards.", practice: "Explain why encryption does not remove the need for access control." },
      { title: "Network change control", note: "Firewall, route, and service changes should be approved, reversible, and observable.", practice: "Draft a rollback step for a fictional firewall change." },
      { title: "Networking recap", note: "Good network practice combines clear ownership, minimal exposure, careful monitoring, and written scope.", practice: "Complete the scoped asset review mission." },
    ],
  },
  {
    id: "web", code: "VOL 06", title: "Web Security & Hardening", accent: "violet",
    description: "Study web security from the defensive side: scope, session protection, input handling, headers, configuration, and clear remediation.",
    lawfulUse: "Assess web applications only with explicit written permission, approved accounts, defined test windows, and an owner ready to receive findings.",
    boundary: "The browser utilities in CYBERFORGE only inspect local input format. They never contact, proxy, scan, or attack a website.",
    topics: [
      { title: "Web application scope", note: "A web assessment scope names domains, APIs, accounts, time limits, and prohibited actions.", practice: "Write a fictional scope for lab-web only." },
      { title: "HTTP request anatomy", note: "A request includes method, path, headers, and sometimes a body; each part can carry security meaning.", practice: "Label the parts of a sample GET request on paper." },
      { title: "Response anatomy", note: "Responses communicate status, headers, and content; security review begins by understanding expected behavior.", practice: "Interpret a 200, 403, and 429 from the virtual route inventory." },
      { title: "Authentication design", note: "Login flows need safe password handling, MFA options, generic errors, rate limits, and recovery controls.", practice: "Trace the login-rate-limit event in the sample logs." },
      { title: "Authorization design", note: "Authorization decides what an authenticated identity may do; it should be enforced server-side at every relevant path.", practice: "Explain the meaning of the virtual /admin 403 response." },
      { title: "Session management", note: "Sessions should expire appropriately, be protected in transit, and be invalidated at meaningful security events.", practice: "List two reasons an application should rotate a session." },
      { title: "Input validation", note: "Validate type, length, format, and authorization near the server-side trust boundary.", practice: "Design a harmless validation rule for a display-name field." },
      { title: "Parameterized queries", note: "Prepared or parameterized queries separate data from commands and reduce injection risk.", practice: "Read the sqlmap defensive lesson without payload testing." },
      { title: "Output encoding", note: "Encode output for the context where it is displayed so user-controlled text is treated as data.", practice: "Describe why text escaping differs across HTML and URLs." },
      { title: "Content Security Policy", note: "CSP helps constrain which resources a browser may load and should be tailored and tested.", practice: "Read the virtual headers.conf sample." },
      { title: "Frame protection", note: "Frame controls reduce UI redress risk when an application should not be embedded elsewhere.", practice: "Locate X-Frame-Options in the sample configuration." },
      { title: "MIME safety", note: "Content type controls help browsers handle resources consistently and reduce unexpected interpretation.", practice: "Locate X-Content-Type-Options in the sample configuration." },
      { title: "Referrer policy", note: "Referrer policy governs what URL information may be shared during navigation and resource requests.", practice: "Explain why a strict policy can reduce accidental disclosure." },
      { title: "Secure cookies", note: "Cookie flags influence transport, script access, and cross-site behavior; they should match the application’s risk.", practice: "List three cookie attributes to review in an authorized application." },
      { title: "Rate limiting", note: "Rate limiting slows abusive patterns while preserving legitimate access and an escalation path for users.", practice: "Use grep to identify the 429 training event." },
      { title: "Error handling", note: "Helpful errors should guide legitimate users without revealing secrets, internals, or stack traces.", practice: "Rewrite an overly detailed error as a safe user message." },
      { title: "Dependency hygiene", note: "Dependencies need version awareness, provenance checks, timely updates, and a rollback strategy.", practice: "Create a short review checklist for a new library." },
      { title: "Secure deployment", note: "Deployment should use secrets management, hardened configuration, logging, backups, and reviewable changes.", practice: "Add a verification step to a fictional deployment checklist." },
      { title: "OWASP-aligned testing", note: "A methodical guide helps teams cover categories consistently, but scope and safe handling remain essential.", practice: "Read the WSTG reference listed in the Study Sources file." },
      { title: "Web-hardening recap", note: "Secure web delivery is a collaboration among builders, operators, reviewers, and accountable owners.", practice: "Complete Mission 3 in the CYBERFORGE terminal." },
    ],
  },
  {
    id: "evidence", code: "VOL 07", title: "Logs, Evidence & Incident Response", accent: "amber",
    description: "Learn how to turn limited, authorized evidence into a defensible timeline, a measured conclusion, and useful next steps.",
    lawfulUse: "Handle incident artifacts only under the organization’s policy, with access controls and data minimization appropriate to the situation.",
    boundary: "CYBERFORGE provides fictional lab logs. Do not paste real sensitive logs, credentials, customer data, or incident material into public tools.",
    topics: [
      { title: "What counts as evidence", note: "Evidence is any relevant, preserved observation that can support or challenge a claim.", practice: "Name three fields in the virtual chain-of-custody note." },
      { title: "Collection context", note: "Record the source, collector, time, method, and reason for collection before analysis begins.", practice: "Create a fictional collection record with no personal data." },
      { title: "Chain of custody", note: "A chain of custody records handling and transfer so others can understand the artifact’s history.", practice: "Open evidence/chain-of-custody.txt." },
      { title: "Preservation", note: "Preserve an original before transformations, and note any copies or derived analysis artifacts.", practice: "Explain why a copy is safer for text-processing practice." },
      { title: "Log sources", note: "Authentication, web, system, endpoint, and network logs each illuminate different parts of an event.", practice: "List the three virtual log sources in CYBERFORGE." },
      { title: "Time normalization", note: "Events need a consistent timezone and clock-quality note before cross-source comparison.", practice: "Order the sample authentication events by time." },
      { title: "Event baselines", note: "A baseline distinguishes ordinary activity from a pattern that needs investigation.", practice: "Describe normal and unusual behavior in a fictional login system." },
      { title: "Authentication failures", note: "Repeated failures can reflect mistakes or abuse; investigate context and defensive control response.", practice: "Use grep failed logs/auth.log." },
      { title: "Rate-limit controls", note: "A rate limit can reduce repeated attempts and generate useful monitoring evidence.", practice: "Find the 429 response in web-access.log." },
      { title: "Triage questions", note: "Ask what happened, which assets matter, what is known, what is missing, and who owns the next action.", practice: "Turn one log observation into five triage questions." },
      { title: "Hypotheses", note: "A hypothesis is a testable explanation, not a conclusion; record what evidence would confirm or weaken it.", practice: "Write a cautious hypothesis about the virtual failed logins." },
      { title: "False positives", note: "Alerts can be benign, incomplete, duplicated, or misconfigured, so correlation matters.", practice: "Give one non-malicious explanation for repeated login failures." },
      { title: "Containment thinking", note: "Containment aims to limit harm while preserving business needs and useful evidence.", practice: "Name one proportional, owner-approved containment action conceptually." },
      { title: "Eradication and recovery", note: "Recovery should address root causes, restore safely, and verify protections rather than merely closing an alert.", practice: "Add a validation step to a fictional recovery plan." },
      { title: "Communications", note: "Incident communication should be timely, factual, audience-aware, and free of speculation.", practice: "Write a two-sentence status update based on the lab event." },
      { title: "Severity and impact", note: "Severity combines likelihood, scope, business impact, and confidence; it should be explained, not guessed.", practice: "List evidence needed before assigning a high severity." },
      { title: "Lessons learned", note: "A post-incident review improves controls, playbooks, ownership, and training without blame.", practice: "Identify one lesson from the virtual rate-limit event." },
      { title: "Evidence-led reports", note: "Reports distinguish fact, interpretation, limitation, and recommendation so readers can act responsibly.", practice: "Use the incident-notes sample as a structure guide." },
      { title: "Privacy during response", note: "Collect only what is needed, protect access, and avoid spreading sensitive details during an investigation.", practice: "Identify data to redact from a public training example." },
      { title: "Response recap", note: "Good response work combines calm triage, preservation, proportional action, and transparent follow-through.", practice: "Summarize the lab incident in a short evidence-first note." },
    ],
  },
  {
    id: "scripting", code: "VOL 08", title: "Scripting & Automation Basics", accent: "blue",
    description: "Learn to automate safe, repeatable personal tasks through readable scripts, controlled inputs, and cautious dependency choices.",
    lawfulUse: "Automate only tasks you are allowed to perform. Keep actions visible, reversible, rate-conscious, and documented.",
    boundary: "CYBERFORGE does not evaluate arbitrary code, run scripts, or allow background automation. It teaches review and design concepts only.",
    topics: [
      { title: "Automation with intent", note: "Automation should solve a clear, bounded task better than a manual process and include a safe stop condition.", practice: "Name a personal task that can be automated without contacting another system." },
      { title: "A script’s purpose", note: "Begin with a plain-language purpose, inputs, outputs, expected side effects, and owner.", practice: "Write a script header for a fictional local log summary." },
      { title: "Shebang lines", note: "A shebang indicates which interpreter should run a script and should match the expected environment.", practice: "Inspect the header in the virtual triage.sh file." },
      { title: "Variables", note: "Variables make scripts reusable, but quoting and validation prevent data from being misread as commands.", practice: "Describe a safe variable name for a local report path." },
      { title: "Arguments", note: "Arguments are inputs supplied at run time; scripts should validate them before use.", practice: "Write an expected argument description for a log filename." },
      { title: "Exit codes", note: "Exit codes indicate success or failure to the calling environment and should be handled explicitly.", practice: "Explain why a failure should not silently look successful." },
      { title: "Conditionals", note: "Conditionals express decisions based on checked facts and should avoid hidden assumptions.", practice: "Write a plain-language if/then decision for a missing file." },
      { title: "Loops", note: "Loops repeat work, so define the collection, rate, boundaries, and exit behavior first.", practice: "Describe a local loop that reviews filenames without changing them." },
      { title: "Functions", note: "Functions group a small well-named responsibility and make review easier.", practice: "Name two functions for a local notes-cleanup script." },
      { title: "Quoting input", note: "Quote file paths and user-supplied values so spaces and special characters are handled predictably.", practice: "Explain why an unquoted filename can be risky." },
      { title: "Input validation", note: "Reject unexpected input early and present a clear error rather than guessing what the user intended.", practice: "Create one validation rule for a report filename." },
      { title: "Logging script behavior", note: "A script’s own logs should say what it did, when, with which safe inputs, and whether it succeeded.", practice: "Draft two example log lines for a local report task." },
      { title: "Dry-run design", note: "A dry-run previews intended actions without changing data, which supports review and trust.", practice: "Describe the output of a dry-run cleanup tool." },
      { title: "Error handling", note: "Handle expected failures, preserve useful context, and avoid exposing secrets in error output.", practice: "Rewrite a vague error into a helpful safe message." },
      { title: "Dependencies", note: "Every dependency adds maintenance and supply-chain responsibility, so minimize and verify them.", practice: "List three checks before adding a package." },
      { title: "Python safety", note: "Python is useful for local data handling, but code from unknown sources should be read and tested first.", practice: "Read the Python conceptual prompt in CYBERFORGE." },
      { title: "Shell safety", note: "Shell scripts are powerful because they invoke commands, making small, explicit steps essential.", practice: "Inspect the virtual triage script rather than executing an unknown file." },
      { title: "Version control", note: "Version control explains what changed and why, helping teams review and safely revert work.", practice: "Use git log in the virtual repository." },
      { title: "Documentation", note: "A good README explains setup, safe use, limitations, input formats, and how to stop or recover.", practice: "Outline a README for a local study helper." },
      { title: "Automation recap", note: "Professional automation is readable, constrained, observable, and designed to fail safely.", practice: "Draft a no-network script idea that supports your study routine." },
    ],
  },
  {
    id: "kali", code: "VOL 09", title: "Kali Methodology & Tool Literacy", accent: "lime",
    description: "Understand the role, limitations, and safe workflow around common Kali tools without turning the public learning console into an execution environment.",
    lawfulUse: "Use a security-testing tool only against assets explicitly named in a written authorization or a deliberately vulnerable practice lab you control.",
    boundary: "CYBERFORGE demonstrates a restricted virtual lab only. Credential guessing, exploitation, wireless capture, and external scanning are intentionally unavailable.",
    topics: [
      { title: "Method before tools", note: "A tool does not replace a scope, an objective, safe handling rules, or a remediation plan.", practice: "Write four questions to answer before selecting any tool." },
      { title: "Rules of engagement", note: "Rules of engagement define systems, methods, timing, contacts, data handling, and stop conditions.", practice: "Create a fictional rule that prohibits production-impact testing." },
      { title: "Asset discovery concepts", note: "Asset awareness begins with owner-provided inventories and authorized visibility, not blind exploration.", practice: "Read the virtual asset review mission." },
      { title: "Nmap methodology", note: "Nmap can support authorized service awareness, but results are a starting point for owner-validated review.", practice: "Run nmap 10.42.0.12 only in CYBERFORGE." },
      { title: "Service validation", note: "An open port suggests a reachable service, not permission to interact beyond the authorized plan.", practice: "Interpret the simulated SSH and HTTP entries." },
      { title: "Web observation methodology", note: "Web review should prioritize safe configuration, session, input, and authorization checks with approved accounts.", practice: "Read the nikto virtual observation response." },
      { title: "Route inventory concepts", note: "Known application routes should be inventoried with authorization and used to improve ownership and access control.", practice: "Use the contained gobuster lesson only." },
      { title: "Parameter handling", note: "Testing input handling is a defensive design review, not permission to deliver destructive payloads.", practice: "Read the sqlmap training review response." },
      { title: "Web proxies as a workflow", note: "A proxy can support authorized request review, but only with approved accounts and explicit boundaries.", practice: "Open the burpsuite safe workflow guidance." },
      { title: "Packet interpretation", note: "Packet metadata can explain a flow, but collection must respect privacy, policy, and physical authorization.", practice: "Read the tcpdump simulated metadata." },
      { title: "Credential protection", note: "Credential guessing and cracking can harm accounts and people; use policy review, MFA, and rate limiting instead.", practice: "Read the blocked-tool explanation for hydra or hashcat." },
      { title: "Exploit frameworks", note: "Exploit frameworks can cause impact even in error; public training should emphasize remediation and lab discipline.", practice: "Read the metasploit boundary response." },
      { title: "Wireless boundaries", note: "Radio capture and monitor-mode work affect physical environments and require explicit owner authorization.", practice: "Read the wireless-tool boundary response." },
      { title: "Tool output hygiene", note: "Save only necessary output, protect it as evidence, and remove sensitive data from reports.", practice: "List three fields to redact from a fictional tool report." },
      { title: "False confidence", note: "A tool can miss issues or produce noisy signals; combine automated observations with contextual verification.", practice: "Explain why a clean result is not proof of complete security." },
      { title: "Severity with restraint", note: "Rate impact using evidence, affected asset context, exploitability, and uncertainty rather than dramatic language.", practice: "Write a cautious severity rationale for a missing header." },
      { title: "Remediation ownership", note: "A finding is useful only when the responsible team can understand the issue, priority, and recommended fix.", practice: "Add an owner and due-date field to a sample finding." },
      { title: "Retesting", note: "Retesting confirms a fix in the approved environment and records what changed without expanding scope.", practice: "Write three checks for a retest plan." },
      { title: "Professional tool selection", note: "Select the smallest set of methods that can answer the authorized question with the least risk.", practice: "Choose a non-invasive observation for the virtual lab." },
      { title: "Kali methodology recap", note: "Professional security work is defined by authorization, restraint, evidence, remediation, and accountable communication.", practice: "Complete Mission 4 in CYBERFORGE." },
    ],
  },
  {
    id: "reporting", code: "VOL 10", title: "Professional Reporting & Growth", accent: "violet",
    description: "Close the loop from careful observation to a clear report that an owner can understand, prioritize, and act on.",
    lawfulUse: "Write reports for the authorized owner, protect sensitive evidence, and distinguish observed facts from assumptions.",
    boundary: "Do not publish findings, customer data, screenshots, or technical details outside the approved audience and disclosure process.",
    topics: [
      { title: "The purpose of a report", note: "A report helps an owner understand risk, evidence, limitations, and a practical next action.", practice: "Write one sentence describing who your fictional report serves." },
      { title: "Executive summary", note: "An executive summary describes the most important result, affected area, and decision needed in clear language.", practice: "Summarize the lab rate-limit result in two sentences." },
      { title: "Scope statement", note: "A scope statement states what was reviewed and, just as importantly, what was not reviewed.", practice: "Add exclusions to a fictional lab report." },
      { title: "Methodology", note: "Methodology explains the safe process used so readers can understand confidence and limitations.", practice: "List the virtual commands used in Mission 1." },
      { title: "Evidence references", note: "Reference artifacts by stable identifiers, source, time, and handling context rather than copying unnecessary content.", practice: "Use CF-LAB-042 as a fictional evidence reference." },
      { title: "Finding titles", note: "A finding title should be specific, neutral, and understandable without sensational language.", practice: "Rewrite 'Critical problem' as an evidence-led title." },
      { title: "Impact explanation", note: "Impact describes the realistic consequence for an asset, user, process, or organization if a weakness is not addressed.", practice: "Describe the impact of missing rate limits in plain language." },
      { title: "Likelihood and confidence", note: "Be explicit about what you know, what you infer, and what needs confirmation from the owner.", practice: "Write one limitation for a static log review." },
      { title: "Remediation guidance", note: "Guidance should be prioritized, technically credible, owner-aware, and testable after change.", practice: "Draft a remediation for an overly permissive file mode." },
      { title: "Compensating controls", note: "When an immediate fix is not possible, a temporary control can reduce risk while a durable change is planned.", practice: "Name one temporary control for a fictional exposed admin page." },
      { title: "Retest criteria", note: "A retest should state the expected evidence of success and the environment in which it will be checked.", practice: "Add a successful outcome to a sample remediation." },
      { title: "Prioritization", note: "Prioritize by impact, likelihood, asset importance, exposure, and available mitigation—not by fear alone.", practice: "Rank three fictional housekeeping issues with reasoning." },
      { title: "Writing without blame", note: "Focus on systems, controls, and evidence so teams can improve without hiding information.", practice: "Rewrite a blaming sentence as a process improvement note." },
      { title: "Stakeholder communication", note: "Different audiences need different levels of detail, but all deserve accurate context and next steps.", practice: "Choose what an engineer and an executive each need to know." },
      { title: "Responsible disclosure", note: "Follow the owner’s disclosure policy, minimize detail to outsiders, and provide time for remediation.", practice: "Describe why public posting is not the first step for a private finding." },
      { title: "Portfolio ethics", note: "A portfolio should demonstrate safe labs, documented permission, learning outcomes, and respectful redaction.", practice: "List three safe artifacts you could include in a student portfolio." },
      { title: "Career learning habits", note: "Security careers depend on clear writing, technical fundamentals, ethical judgment, and continuous practice.", practice: "Create a monthly study goal using CYBERFORGE paths." },
      { title: "Peer review", note: "A second reviewer can catch unclear claims, missing scope, assumptions, and sensitive data leaks.", practice: "Make a five-point peer-review checklist." },
      { title: "Professional resilience", note: "When an investigation is stressful, slow down, record facts, ask for help, and follow the escalation plan.", practice: "Write a personal pause-and-escalate rule." },
      { title: "Reporting recap", note: "Your value comes from helping owners make safer decisions with accurate evidence and responsible communication.", practice: "Draft the closing paragraph for the CYBERFORGE lab report." },
    ],
  },
];

const noteFrames = [
  "Start with the plain-language meaning before learning any shortcut or tool name.",
  "Connect the concept to an accountable asset, a real owner, and a known purpose.",
  "Identify the smallest safe observation that could improve a defensive decision.",
  "Write down what this concept cannot prove by itself; limits are part of good analysis.",
  "Practice reading the evidence first, then make only a measured conclusion.",
  "Treat configuration, output, and documentation as material that needs review before change.",
  "Use a dedicated, disposable lab for experiments and preserve a known-good baseline.",
  "Prefer a clear, reversible step over a broad action that is difficult to explain later.",
  "Record the source and time of an observation so another learner can follow your reasoning.",
  "Separate fact, interpretation, and recommendation in your notes.",
  "Choose the least-privileged method that answers the authorized learning question.",
  "Avoid collecting, copying, or sharing information that does not support the stated objective.",
  "When a result seems surprising, validate it with a second safe source before escalating.",
  "Use a short checklist to make the safe behavior repeatable under time pressure.",
  "Turn the lesson into a practical habit that works even when no tool is available.",
  "Make any recommendation specific enough that an owner can test whether it is complete.",
  "Keep the human impact in view: availability, privacy, and trust matter alongside technical detail.",
  "Document the next responsible step and the person or team that should own it.",
  "End with a review question that checks understanding rather than memorization.",
  "Carry the method forward: authorized scope, minimal risk, evidence, remediation, and clear communication.",
];

export const studyVolumes = volumes;
export const studyPages: StudyPage[] = volumes.flatMap((volume, volumeIndex) => volume.topics.map((topic, topicIndex) => ({
  number: volumeIndex * 20 + topicIndex + 1,
  volume,
  topic,
  note: noteFrames[topicIndex],
})));
